 
 spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql:///abc
    username: root
  profiles:
    active: default
---
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: root
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: System
  config:
    activate:
      on-profile: test
---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    type: org.apache.commons.dbcp2.BasicDataSource
    url: jdbc:mysql:///abc
    username: root
  config:
    activate:
      on-profile: uat
---
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: root
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: System
  config:
    activate:
      on-profile: prod
